// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJtp2d3kppDX4C4h5xIA5q6d8uKFtcR0U',
    appId: '1:285407888195:web:b9260b163478bf16c2a5f6',
    messagingSenderId: '285407888195',
    projectId: 'wardrobebeshka',
    authDomain: 'wardrobebeshka.firebaseapp.com',
    storageBucket: 'wardrobebeshka.firebasestorage.app',
    measurementId: 'G-BV9EMGZ7SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoNK7pjP2aW2KuYGHBBr4suSs_xr86n_4',
    appId: '1:285407888195:android:5327aef050c5ae69c2a5f6',
    messagingSenderId: '285407888195',
    projectId: 'wardrobebeshka',
    storageBucket: 'wardrobebeshka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkhik-Fj1K7HCUtAZ9TgTVRAW9S7BFERc',
    appId: '1:285407888195:ios:ef1a6f4aa5e6875cc2a5f6',
    messagingSenderId: '285407888195',
    projectId: 'wardrobebeshka',
    storageBucket: 'wardrobebeshka.firebasestorage.app',
    iosBundleId: 'com.example.chatapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkhik-Fj1K7HCUtAZ9TgTVRAW9S7BFERc',
    appId: '1:285407888195:ios:ef1a6f4aa5e6875cc2a5f6',
    messagingSenderId: '285407888195',
    projectId: 'wardrobebeshka',
    storageBucket: 'wardrobebeshka.firebasestorage.app',
    iosBundleId: 'com.example.chatapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJtp2d3kppDX4C4h5xIA5q6d8uKFtcR0U',
    appId: '1:285407888195:web:25284cc328a0ccebc2a5f6',
    messagingSenderId: '285407888195',
    projectId: 'wardrobebeshka',
    authDomain: 'wardrobebeshka.firebaseapp.com',
    storageBucket: 'wardrobebeshka.firebasestorage.app',
    measurementId: 'G-6EBDBLL7GV',
  );
}
